# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VisToggler
                                 A QGIS plugin
 Toggle visibility of layers with keystrokes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-28
        copyright            : (C) 2020 by Stafford Smith
        email                : staffordsmith83@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VisToggler class from file VisToggler.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vis_toggler import VisToggler
    return VisToggler(iface)
